alter table time_entry drop constraint FK42EDB080A45F9215;
alter table xdir drop constraint FK3811157B66B0D0;
alter table story drop constraint FK68AF8F596607D1C;
alter table story drop constraint FK68AF8F5151239BD;
alter table iteration drop constraint FK8904EEDD8A94A401;
alter table note drop constraint FK33AFF2A62F61B7;
alter table notification_receivers drop constraint FK90D2EE1032DA9A45;
alter table notification_receivers drop constraint FK90D2EE108A94A401;
alter table task drop constraint FK3635856662D8A5;
alter table xfile drop constraint FK6CAF9F4B0A1860D;
drop table datasample if exists;
drop table person_role if exists;
drop table attribute if exists;
drop table time_entry if exists;
drop table person if exists;
drop table xdir if exists;
drop table story if exists;
drop table iteration if exists;
drop table note if exists;
drop table project if exists;
drop table integration if exists;
drop table permission if exists;
drop table role if exists;
drop table history if exists;
drop table notification_receivers if exists;
drop table task if exists;
drop table xfile if exists;
drop table identifier;